### ISSUE TITLE
Can not remove monitor streams

### ISSUE THREAD

**Issue by JoeldelPilar** [Eyevinn/hls-monitor#40]
Hi!

I am using the app HLS Stream Monitor and I found it really useful. However, I have faced an issue deleting streams that I monitor. I can't delete monitored streams using:

/monitor | DELETE | Delete all monitored streams
or
/monitor/:monitorId | DELETE | Delete a specific stream

An example:
curl -X 'DELETE' \
  'https://awatenant-hlsmonitorawa.eyevinn-hls-monitor.auto.prod.osaas.io/monitor/20c07128-be3c-41fc-8253-a523ffbba19d' \
  -H 'accept: application/json'
results in:
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "Cannot read properties of null (reading 'streams')"
}

Any idea what I am doing wrong?

Keep up the great work!

_Originally posted by @anderswassen in https://github.com/Eyevinn/osaas/discussions/40_

**Comment by birme** [comment]
I recognize that the documentation could be more clear on this and the error more gracefully handled. The problem here is that `DELETE /monitor/:monitorId` expect you to provide which stream to delete from that monitor. That is provided in the request body:

```
{
  "streams": ["mystream1.m3u8"]
}
```

**Comment by birme** [comment]
Found that the Swagger documentation did not include this so I will fix that.
